use std::io;

fn main() -> Result<(), io::Error> {
    println!("Todo Resolve All");
    Ok(())
}
